cd ~
DOMAIN_MODE=NON_EXPRESS
readonly DOMAIN_MODE
SMUS_PROJECT_DIR=/home/sagemaker-user/src
readonly SMUS_PROJECT_DIR
LOGNAME=Revanth
readonly LOGNAME
export AMAZON_Q_SIGV4=true
export Q_CLI_CLIENT_APPLICATION=SMUS_JUPYTER_LAB
readonly Q_CLI_CLIENT_APPLICATION
